// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWUicni-22VOm8AST4L_zzm1bUFjNaYks',
    appId: '1:989643553055:web:66186ea6acbece938e982a',
    messagingSenderId: '989643553055',
    projectId: 'appprimeiro-a15e4',
    authDomain: 'appprimeiro-a15e4.firebaseapp.com',
    storageBucket: 'appprimeiro-a15e4.firebasestorage.app',
    measurementId: 'G-QLEWW4ZCJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABuEaeuvy9NSOiKiqGP2uEjZNqBl5sXCc',
    appId: '1:989643553055:android:a5dd700b0b50004b8e982a',
    messagingSenderId: '989643553055',
    projectId: 'appprimeiro-a15e4',
    storageBucket: 'appprimeiro-a15e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfV2dMU5sJwYpv_L-KWpg1UxCY__oxbCM',
    appId: '1:989643553055:ios:75e88028e3aafd318e982a',
    messagingSenderId: '989643553055',
    projectId: 'appprimeiro-a15e4',
    storageBucket: 'appprimeiro-a15e4.firebasestorage.app',
    iosBundleId: 'com.example.equadras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfV2dMU5sJwYpv_L-KWpg1UxCY__oxbCM',
    appId: '1:989643553055:ios:75e88028e3aafd318e982a',
    messagingSenderId: '989643553055',
    projectId: 'appprimeiro-a15e4',
    storageBucket: 'appprimeiro-a15e4.firebasestorage.app',
    iosBundleId: 'com.example.equadras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWUicni-22VOm8AST4L_zzm1bUFjNaYks',
    appId: '1:989643553055:web:3c6505cccda9aa658e982a',
    messagingSenderId: '989643553055',
    projectId: 'appprimeiro-a15e4',
    authDomain: 'appprimeiro-a15e4.firebaseapp.com',
    storageBucket: 'appprimeiro-a15e4.firebasestorage.app',
    measurementId: 'G-091543W7HY',
  );
}
